# Growing media

A growing medium is a material through which plant roots grow and from which they extract water and nutrients.

## Functions of growing media

- physical support
    - growing medium must support the plant or cutting but stay porous
    - large plants need ballast in the medium to hold plant upright

- aeration
    - plant roots need oxygen so they can convert sugar into energy to grow
    - this process produces carbon dioxide, which needs to be removed from the root zone to prevent toxic concentrations building up
    - this gas exchange occurs in the macropores
    
- water supply
    - growing media hold water in the micropores
    - they need enough porosity to store the required amounts of water
    - organic material is one of the main components of growing media that absorb and hold water
    
- nutrient supply
    - most nutrients are obtained by a plant through its roots from the potting medium
    - most nutrients are cations
    - the potting medium must contain materials which can hold these cations
    - the capacity of a material to hold cations is *cation exchange capacity* (CEC)
    - potting media components can vary widely in CEC
    
 
## Physical properties of growing media

- water-holding capacity
    - this is the percentage of total pore space that stays filled with water after letting water drain under gravity
    - a growing medium needs good water holding capacity and good drainage
    - it has good drainage if it has enough macropores to let water drain away and prevent waterlogging
    - compaction is important to take into account - if the medium is compacted, the proportion of macropores is reduced and the roots will be deprived of oxygen
    
- aeration
    - the percentage of pore space that is filled with air after excess water has drained away is aeration
    - oxygen is supplied to and carbon dioxide is removed from the root zone through the macropores
    - a good growing medium needs a high percentage of macropores
    
- porosity
    - total porosity is the sum of the volume of macropores and the volume of micropores - plants need both adequate macropores and micropores
    - a medium with mainly larger particles will have higher aeration and lower water-holding capacity than a medium with mainly smaller particles, which will have lower aeration and higher water-holding capacity - neither is probably satisfactory
    

## Chemical properties of growing media
    
- fertility
    - growing media must supply plants with the necessary mineral nutrients
    - the fertility level that is maintained in media depends on several factors
        - some plants grow better at low nutrient levels
        - low nutrient levels can help prevent damping off during the establishment phase
        - some beneficial microorganisms require low nutrient levels to become established - e.g. mycorrhizal fungi
        
 - pH
    - pH affects the availability of mineral nutrients to plants
    - e.g. iron chlorosis, a common nutrient deficiency, is caused by high pH; the availability of P drops at extreme pH as it binds with Fe and Al at low pH and Ca at high pH
    
- cation exchange capacity (CEC)
    - CEC is the ability of a material to hold onto cations
    - CEC reflects the ability of a growing medium to store nutrients and so helps indicate how often fertilising might be needed


## Biological properties of growing media
    
- growing media components may contain pathogenic bacteria or fungi or weed seeds
- growing media need to be obtained from suppliers that have carried out necessary treatments on components to ensure media are free of pathogens and seeds
- vermiculite and perlite are sterile because they are manufactured at high temperatures
- peat moss from reliable suppliers is free of pathogens
- well-made compost is free of pathogens because temperatures reached during composting kill most pathogens
- in the final stages of composting, beneficial microorganisms increase - another benefit of composting!


## Components of growing media

- Sphagnum peat moss
    - this type of peat moss has uniform quality and, because of this, is the only type used but there are sustainability considerations around using it
    - it is used in limited amounts in germination mixes

(Most of the material above comes from *Tropical Nursery Manual*.)


## Growing media for particular purposes

Qualities of growing media for particular uses are listed below.

The qualities of growing media must match the growth phase of the plants: seed germination / rooting cuttings, potting up, potting on.



### Seed propagation

- free from pests and disease
- high water-holding capacity to maintain uniform moisture around seeds


### Cuttings

- free from pests and disease
- very porous
    - good drainage, as cuttings are often misted and so the growing medium must not become waterlogged
    - high aeration or air-filled porosity (i.e. a high percentage of macropores) to encourage root growth



### Transplant or potting on media

Plants in this growth phase have actively growing roots, shoots and leaves, can support themselves, absorb nutrients and produce their own food.

- free from pests and disease
- coarser than seed propagation or cuttings media
- well-aerated and drained (i.e. holding more air (oxygen))
- good water-holding and nutrient holding capacity to satisfy the needs of actively growing plants (i.e. actively growing roots, shoots and leaves)
    - initially, water-holding capacity is less than seed raising and tubing up mixes but increases as organic components decompose
- heavy enough so plants stay upright (i.e. more sand)
- may contain some fertiliser

N.B. The type of potting mix used for potting on depends on the type of plant, the conditions (e.g. more protected or less protected) it will grow under, season and irrigation method. Potting on mixes can be general or made to suit the needs of particular plants (e.g. orchids, azaleas).
    
    
### Establishment media

In this growth phase, plants have well-developed root and shoot systems and can support themselves, absorb nutrients and produce and store their own food.

They need to be able to cope with an environment with few climatic controls.

The emphasis here is on keeping the plant healthy and not encouraging it to grow excessively.

- free from pests and disease
- lower aeration and drainage than other mixes to allow for slower growth rates and less maintenance
- high water-holding and nutrient-holding capacity (due to less maintenance)
- ballast (i.e. more sand) for stability
- for plants remaining in containers for the long-term, the media must resist decomposing - the particles must remain stable to maintain growing conditions; sand can be used to provide the smallest particles
    



