# Glossary


**There are sections below for plant-related and soil-related terms**

## Plant-related terms

**endemic** a plant that is endemic to a particular geographical region has a natural distribution that is confined to that particular geographical region

**native** if a plant is native to a particular area, it occurs naturally in that area but is not confined to that area

<br>

**front-line salt tolerant** This refers to plants that can tolerate full coastal exposure and that have foliage that can withstand salt spray and salt-laden winds 

(Reference for front-line and second-line salt tolerance: https://www.austplants.com.au/resources/Pictures/Central%20Coast%20District%20Group/4COSTALP.pdf

For NSW central coast plant lists, also see https://www.austplants.com.au/resources/Documents/Central-Coast-Documents/Fact%20Sheets/Coastal%20Plants%20v4%20HM%20and%20v4%20BM.pdf).

**second-line salt tolerant** This refers to plants that can tolerate moderate coastal exposure and that grow best if protected from salt-laden winds.  In exposed positions on the coast, they could be grown behind a protective screen of front-line salt tolerant plants.

<br>

**hardwood**

- Wood or wood products from flowering trees (broad-leaved tree species), such as eucalypts, irrespective of the physical hardness of the wood (https://www.agriculture.gov.au/abares/forestsaustralia/glossary/search?name_1=Hardwood).
- Another (horticultural) definition: Wood that undergoes secondary growth

**softwood**

- Wood or wood products from conifers, irrespective of the physical softness of the wood.

- Another (horticultural) definition: Wood that does not undergo secondary growth

<br>

**potting up** This is moving seedlings or rooted cuttings to their first pot.

**potting on, growing on** This is moving a plant that has outgrown its pot into a larger pot.

<br>

**monoecious** a species of plant that has separate female and male flowers on the **same** plant (from mon(o)-, one, and Greek oikon, house - pronounced with three syllables, mo-'noe-cious).

**dioecious** a species of plant that has separate female and male flowers, with each type on **separate** plants (from di-, two, and Greek oikon, house - pronounced with three syllables, di-'oe-cious).

<br>

**shrub** a woody plant less than 8 metres tall, often with many stems that arise at or near the base

**tree** a woody plant more than 5 metres tall, usually with a single stem

- small tree: 5 - 10 metres tall

- medium tree: 10 - 20 metres tall

- large tree: 20+ metres tall

The above ranges are a bit rough!

(Definition of shrub and tree from: https://www.anbg.gov.au/aust-veg/veg-map.html

Height ranges from: https://www.wa.gov.au/system/files/2020-09/FPC-species-information.pdf)

<br>
<br>

## Soil-related terms


**colloid** Particles smaller than about 1 $\mu\,\texttt{m}$ are colloids

**mineralisation** When plant material decomposes, elements that were part of organic compounds in the plant material are converted to inorganic forms in a process called *mineralisation*. Some of these elements are used by micro-organisms for growth (*immobilisation* of elements) and what is left over (if anything) is mineralised. For example, N, P and S end up as NH~4~^+^, H~2~PO~4~^-^ and SO~4~^2-^ ions and about half the C is released as CO~2~. 

